### ISSUE TITLE
Generate and attach detailed timestamps to each response.

### ISSUE THREAD

**Issue by urbanslug** [goodbotai/borq#11]
### Environment
All

### Expected behavior
One should know when a message was answered.
This data can also be sent to Ona along with the answer.

### Actual behavior
We don't store timestamps for when questions were answered.

---

### Implementation plan
- [x] Use the Aggregate module to extract time stamps and associate them with each answer.
- [x] Use the services module to send timestamped answers to Ona.
- [x] Have translations handling be possible to do in borq

### Blocking or related issues
Ona might not support timestamps for each answer.

**Comment by pld** [comment]
Pretty sure Ona does not support timestamps for each answer, one option is to add an additional column for each answer to store these.
