### ISSUE TITLE
Implement user deletion

### ISSUE THREAD

**Issue by urbanslug** [goodbotai/borq#21]
### Environment
All

### Expected behavior
There should be a way to delete users

### Actual behavior
There isn't a way to delete bot users

### Steps to reproduce the behavior
There's just no way to unsubscribe.

---

### Implementation plan

- Implement a way to soft delete a user
- [x] Add a deleteUser function in services
- [x]  Add a config env var for deleted users
- [x] Move a user to a different group
- [ ] version bump

### Blocking or related issues
None
