### ISSUE TITLE
Have schedule be in a users specific timezone

### ISSUE THREAD

**Issue by pld** [goodbotai/borq#23]
### Environment
All

### Expected behavior
Messages to users should be scheduled in their local time-zone

### Actual behavior
Messages for everyone globally are all sent at the same time

### Implementation plan

- Get a users location or timezone from the Facebook API
- If above not possible, ask user
- Store uses timezone in their contact

### Blocking or related issues

Introducing randomness intro scheduler, https://github.com/goodbotai/borq/issues/11, randomness would be within the timezone

**Comment by urbanslug** [comment]
The user's timezone is stored in their Rapidpro contact.

**Comment by pld** [comment]
We can run a flow every 12 hours, if the user's timezone field is X at 12 hours send message then, otherwise send message at the next 12 hour run.

To add randomness (later, not in this issue) we can run it every hour and use a hash to divide the contacts equally and randomly per day among the 12 hour buckets in their time-zone's window.

**Comment by urbanslug** [comment]
## Scheduling
### Requirements/constraints
 - Should be timezone specific
 - In future should not be at the same time every day
 - Campaigns don't recur unlike triggers
 - Triggers can repeat a minimum of daily but not multiple times a day
 - We want to trigger a flow

### Implementation plan
 - [X] Save the user timezone
 - [ ] Save the user registration date
 - [ ] Have a campaign run 24 hours after reg date
 - [ ] Have a cron that resets the campaign via a POST (how often? what time?)
 - [ ] Update reg date for a contact after the webhook is called

## Scheduling with randomness
### Requirements/constraints
 - Random times between 0900 and 2100 local time for a user

### Implementation plan
 - [ ] Have the cron schedule the campaign for +/- x hours after @contact.registration_date

## Agreed upon implementation plan
- [ ] split users into timezone specific groups upon user creation.
- [ ] have different triggers for each group for a time that is appropriate for them

### Reasons
 - Use triggers because they recur
 - We would like to use campaigns but they don't recur however it would be easier to implement randomness by updating the time offset in a campaign event
- With campaigns we need a job that would run every x hours and send a POST to rapidpro to reset the campaign
