### ISSUE TITLE
Allow setting api_host

### ISSUE THREAD

**Issue by urbanslug** [goodbotai/borq#50]
### Environment
Testing

### Expected behavior
We shouldn't use graph.facebook.com for stress and conversation integration testing.

### Actual behavior
We don't allow setting an alternative URL when testing, we always hit graph.facebook.com 

### Steps to reproduce the behavior

---

### Implementation plan
Take advantage of `api_host` facebook bot config in botkit.

- [ ] Add an environment variable API_HOST that expects a URL or IP address (String)
- [ ] Add a check to see if NODE_ENV is `test*`
- When in test evironment 
  - [ ] Check if API_HOST env var has been passed
  - [ ] Set `api_host` in `Botkit.facebookbot` config to env var value or else use invalid URL http://256.256.256.256
- When *not* in testing evironment 
  - [ ] set `api_host` to `undefined`
